#!/system/bin/sh

export PATH=/sbin:/system/sbin:/system/bin:/system/xbin

echo "intellidemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
MAX_FREQ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq)
echo "95" > /sys/devices/system/cpu/cpufreq/intellidemand/up_threshold
echo "85" > /sys/devices/system/cpu/cpufreq/intellidemand/up_threshold_any_cpu_load
echo "75" > /sys/devices/system/cpu/cpufreq/intellidemand/up_threshold_multi_core
echo "1134000" > /sys/devices/system/cpu/cpufreq/intellidemand/two_phase_freq
echo "$MAX_FREQ" > /sys/devices/system/cpu/cpufreq/intellidemand/optimal_freq
echo "810000" > /sys/devices/system/cpu/cpufreq/intellidemand/sync_freq
echo "1350000" > /sys/devices/system/cpu/cpufreq/intellidemand/boostfreq
echo "$MAX_FREQ" > /sys/devices/system/cpu/cpufreq/intellidemand/lmf_active_max_freq
echo "2000000" > /sys/devices/system/cpu/cpufreq/intellidemand/boosttime
