cd micore_tools/$1/initramfs/sbin
chmod 775 busybox
ln -fs busybox [
ln -fs busybox [[
ln -fs busybox awk
ln -fs busybox cat
ln -fs busybox chmod
ln -fs busybox chown
ln -fs busybox cp
ln -fs busybox cpio
ln -fs busybox cut
ln -fs busybox date
ln -fs busybox dmesg
ln -fs busybox echo
ln -fs busybox expr
ln -fs busybox find
ln -fs busybox grep
ln -fs busybox gzip
ln -fs busybox id
ln -fs busybox insmod
ln -fs busybox ln
ln -fs busybox md5sum
ln -fs busybox mkdir
ln -fs busybox mkswap
ln -fs busybox mount
ln -fs busybox mv
ln -fs busybox run-parts
ln -fs busybox sed
ln -fs busybox source
ln -fs busybox sh
ln -fs busybox sleep
ln -fs busybox swapoff
ln -fs busybox swapon
ln -fs busybox sync
ln -fs busybox sysctl
ln -fs busybox rm
ln -fs busybox tee
ln -fs busybox test
ln -fs busybox touch
ln -fs busybox wc
ln -fs busybox unzip
ln -fs busybox umount
